'🐰 Core':
  - changed-files:
      - any-glob-to-any-file: 'packages/core/**'

'🐹 Next':
  - changed-files:
      - any-glob-to-any-file: 'packages/next/**'

'🐸 React':
  - changed-files:
      - any-glob-to-any-file: 'packages/react/**'